// Umumiy konstantalar
module.exports = {
  ROLES: {
    SUPER_ADMIN: 'super_admin',
    ADMIN: 'admin',
    ORGANIZER: 'organizer',
    HOST: 'host',
    PLAYER: 'player',
  },

  STATES: {
    // Komanda
    TEAM_CREATE_NAME: 'team_create_name',
    TEAM_CREATE_TAG: 'team_create_tag',
    TEAM_CREATE_AVATAR: 'team_create_avatar',
    TEAM_CREATE_MANAGER: 'team_create_manager',
    TEAM_CREATE_CONFIRM: 'team_create_confirm',
    TEAM_JOIN_CODE: 'team_join_code',
    TEAM_EDIT_NAME: 'team_edit_name',
    TEAM_EDIT_TAG: 'team_edit_tag',
    TEAM_EDIT_AVATAR: 'team_edit_avatar',
    TEAM_EDIT_BIO: 'team_edit_bio',
    TEAM_EDIT_MANAGER: 'team_edit_manager',

    // Turnir
    TOUR_CREATE_TITLE: 'tour_create_title',
    TOUR_CREATE_IMAGE: 'tour_create_image',
    TOUR_CREATE_DATE: 'tour_create_date',
    TOUR_CREATE_TIME: 'tour_create_time',
    TOUR_CREATE_MODE: 'tour_create_mode',
    TOUR_CREATE_PRIZE: 'tour_create_prize',
    TOUR_CREATE_MAP_TAG: 'tour_create_map_tag',
    TOUR_CREATE_ETAPA: 'tour_create_etapa',
    TOUR_CREATE_MAXTEAMS: 'tour_create_maxteams',
    TOUR_CREATE_DESC: 'tour_create_desc',
    TOUR_CREATE_DEADLINE: 'tour_create_deadline',
    TOUR_CREATE_HOST: 'tour_create_host',
    TOUR_CREATE_CONFIRM: 'tour_create_confirm',
    TOUR_EDIT_FIELD: 'tour_edit_field',
    TOUR_EDIT_VALUE: 'tour_edit_value',
    TOUR_CLONE_DATE: 'tour_clone_date',
    TOUR_CLONE_TIME: 'tour_clone_time',

    // Host
    HOST_SEND_ROOM_ID: 'host_send_room_id',
    HOST_SEND_ROOM_PASS: 'host_send_room_pass',
    HOST_SEND_ROOM_BOTH: 'host_send_room_both',
    HOST_SEND_BROADCAST: 'host_send_broadcast',
    HOST_MATCH_INPUT: 'host_match_input',
    HOST_EDIT_MATCH: 'host_edit_match',
    HOST_PRIZE_INPUT: 'host_prize_input',

    // O'yinchi
    PLAYER_SEND_TO_HOST: 'player_send_to_host',
    PLAYER_PUBG_ID: 'player_pubg_id',

    // Admin
    ADMIN_ADD_USER_ID: 'admin_add_user_id',
    ADMIN_ADD_ROLE: 'admin_add_role',
    ADMIN_BAN_INPUT: 'admin_ban_input',
    ADMIN_UNBAN_INPUT: 'admin_unban_input',
    ADMIN_DM_USER: 'admin_dm_user',
    ADMIN_DM_MSG: 'admin_dm_msg',
    ADMIN_CHANNEL_INPUT: 'admin_channel_input',
    ADMIN_SETTING_EDIT: 'admin_setting_edit',

    // Qidiruv
    SEARCH_QUERY: 'search_query',
  },

  CALLBACK: {
    MENU_TOURNAMENTS: 'menu:tournaments',
    MENU_TEAM: 'menu:team',
    MENU_PROFILE: 'menu:profile',
    MENU_HELP: 'menu:help',
    MENU_ADMIN: 'menu:admin',
    MENU_BACK: 'menu:back',
    MENU_MAIN: 'menu:main',

    // Komanda
    TEAM_CREATE: 'team:create',
    TEAM_JOIN: 'team:join',
    TEAM_MY: 'team:my',
    TEAM_LEAVE: 'team:leave',
    TEAM_CONFIRM: 'team:confirm',
    TEAM_RETRY: 'team:retry',
    TEAM_CANCEL: 'team:cancel',
    TEAM_EDIT: 'team:edit',
    TEAM_EDIT_FIELD: 'team:editf:',
    TEAM_STATS: 'team:stats',
    TEAM_HISTORY: 'team:history',
    TEAM_CAPTAIN_CHANGE: 'team:cc',
    TEAM_CAPTAIN_PICK: 'team:ccp:',
    TEAM_MEMBERS: 'team:members',
    TEAM_KICK: 'team:kick:',
    TEAM_KICK_CONFIRM: 'team:kickc:',

    // Turnir
    TOUR_LIST: 'tour:list',
    TOUR_TODAY: 'tour:today',
    TOUR_UPCOMING: 'tour:upcoming',
    TOUR_FINISHED: 'tour:finished',
    TOUR_OPEN: 'tour:open:',
    TOUR_REGISTER: 'tour:reg:',
    TOUR_CONTACT_HOST: 'tour:contact_host:',
    TOUR_CREATE: 'tour:create',
    TOUR_CONFIRM: 'tour:confirm',
    TOUR_CANCEL: 'tour:cancel',
    TOUR_ASSIGN_HOST: 'tour:ah:',
    TOUR_BROADCAST: 'tour:bc:',
    TOUR_EDIT: 'tour:edit:',
    TOUR_EDIT_FIELD: 'tour:editf:',
    TOUR_TEAMLIST: 'tour:tl:',
    TOUR_PICK_HOST: 'tour:ph:',
    TOUR_DELETE: 'tour:del:',
    TOUR_DELETE_CONFIRM: 'tour:delc:',
    TOUR_PAGE: 'tour:page:',
    TOUR_STANDINGS: 'tour:st:',
    TOUR_CLONE: 'tour:clone:',
    TOUR_CLONE_START: 'tour:clones:',
    TOUR_HISTORY: 'tour:hist',
    TOUR_HISTORY_VIEW: 'tour:hv:',
    TOUR_LINK: 'tour:link:',
    TOUR_STATS: 'tour:stats:',
    TOUR_TEMPLATE: 'tour:tpl',
    TOUR_TEMPLATE_USE: 'tour:tplu:',
    TOUR_TEMPLATE_NEW: 'tour:tpln:',
    TOUR_STAGE: 'tour:stage:',
    TOUR_STAGE_SET: 'tour:stages:',
    TOUR_CALENDAR: 'tour:cal',
    TOUR_CAL_MONTH: 'tour:calm:',
    TOUR_ANNOUNCE: 'tour:anc:',
    TOUR_REPORT: 'tour:rep:',
    TOUR_WINNERS: 'tour:win:',

    // Host
    HOST_TOURS: 'host:tours',
    HOST_OPEN: 'host:open:',
    HOST_ROOM_ID: 'host:rid:',
    HOST_ROOM_PASS: 'host:rpass:',
    HOST_ROOM_BOTH: 'host:rboth:',
    HOST_MSG: 'host:msg:',
    HOST_RESULTS: 'host:res:',
    HOST_MATCH_NEW: 'host:mn:',
    HOST_MATCH_CONFIRM: 'host:mc:',
    HOST_MATCH_LIST: 'host:ml:',
    HOST_MATCH_VIEW: 'host:mv:',
    HOST_MATCH_DELETE: 'host:mdel:',
    HOST_MATCH_DEL_CONFIRM: 'host:mdc:',
    HOST_MATCH_EDIT: 'host:me:',
    HOST_STANDINGS: 'host:st:',
    HOST_PRIZE: 'host:pr:',
    HOST_VOICE: 'host:vc:',
    HOST_VIDEO: 'host:vd:',
    HOST_POLL: 'host:pl:',
    HOST_ANNOUNCE_WINNERS: 'host:aw:',

    // O'yinchi
    USER_PUBG_ID: 'user:pid',
    USER_STATS: 'user:stats',
    USER_ACHIEVEMENTS: 'user:ach',
    USER_LEADERBOARD: 'user:lb',
    USER_LB_MODE: 'user:lbm:',

    // Admin panel
    ADMIN_PANEL: 'admin:panel',
    ADMIN_USERS: 'admin:users',
    ADMIN_TEAMS: 'admin:teams',
    ADMIN_TOURNAMENTS: 'admin:tournaments',
    ADMIN_HOSTS: 'admin:hosts',
    ADMIN_ADMINS: 'admin:admins',
    ADMIN_ORGS: 'admin:orgs',
    ADMIN_BROADCAST: 'admin:broadcast',
    ADMIN_STATS: 'admin:stats',
    ADMIN_SETTINGS: 'admin:settings',
    ADMIN_ADD_ROLE: 'admin:addrole:',
    ADMIN_DEL_ROLE: 'admin:delrole:',
    ADMIN_PAGE: 'admin:page:',
    ADMIN_BAN: 'admin:ban',
    ADMIN_BAN_CONFIRM: 'admin:banc:',
    ADMIN_UNBAN: 'admin:unban:',
    ADMIN_DM: 'admin:dm:',
    ADMIN_LOGS: 'admin:logs',
    ADMIN_ACTIONS: 'admin:act',
    ADMIN_CHANNEL: 'admin:ch',
    ADMIN_SET_EDIT: 'admin:se:',

    // Umumiy
    CANCEL: 'common:cancel',
    SEARCH_START: 'search:start',
    SEARCH_TOUR: 'search:tour',
    SEARCH_TEAM: 'search:team',
    FILTER_TOUR: 'filter:tour',
  },

  LIMITS: {
    MAX_TEAMS_PER_TOURNAMENT: 18,
    MIN_TEAMS_PER_TOURNAMENT: 2,
    MAX_PLAYERS_PER_TEAM: 8,
    MIN_PLAYERS_PER_TEAM: 1,
    MAX_NAME_LEN: 60,
    MAX_DESC_LEN: 400,
    MAX_CAPTION_LEN: 300,
    MAX_PRIZE_LEN: 100,
    MAX_MAP_TAG_LEN: 50,
    MAX_ETAPA_LEN: 30,
    MAX_BIO_LEN: 150,
    MAX_TAG_LEN: 5,
    BROADCAST_DELAY_MS: 60,
    BROADCAST_BATCH: 25,
    PAGE_SIZE: 8,
    TOUR_PAGE_SIZE: 5,
    LOGS_PAGE_SIZE: 20,
    ACTIONS_PAGE_SIZE: 15,
  },

  DEFAULT_MAP: 'Erangel',
  DEFAULT_MODE: 'Squad',
  DEFAULT_MAX_TEAMS: 18,
  DEFAULT_MAX_PLAYERS: 8,

  TEAM_LIST: {
    EMPTY_SLOTS: 2,
    START_INDEX: 3,
    RU_TIMEZONE_DIFF: 2,
  },

  PLACEMENT_POINTS: {
    1: 10,
    2: 6,
    3: 5,
    4: 4,
    5: 3,
    6: 2,
    7: 1,
    8: 1,
  },

  // Achievements
  ACHIEVEMENTS: {
    FIRST_BLOOD: { id: 'first_blood', name: '🥇 Birinchi qon', desc: 'Birinchi kill' },
    HUNDRED_KILLS: { id: 'hundred_kills', name: '💯 100 kill', desc: '100 ta kill' },
    FIVE_WINS: { id: 'five_wins', name: '🏆 5 g\'alaba', desc: '5 marta 1-o\'rin' },
    TEN_MATCHES: { id: 'ten_matches', name: '🎮 10 o\'yin', desc: '10 ta kartada qatnashish' },
    CAPTAIN_MASTER: { id: 'captain_master', name: '👑 Captain', desc: 'Komanda captain\'i' },
    CHICKEN_DINNER: { id: 'chicken_dinner', name: '🍗 Winner Winner', desc: '1-o\'rin' },
  },

  // Team statuses
  TEAM_STATUS: {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
  },

  // Tournament stages
  STAGES: {
    SINGLE: 'single',
    QUARTER: 'quarter',
    SEMI: 'semi',
    FINAL: 'final',
  },

  // Languages
  LANGS: {
    UZ: 'uz',
    RU: 'ru',
    EN: 'en',
  },
};